import Head from "next/head";
import Navbar from "../components/Navbar";
import Sort from "../components/Sort";

export default function Home() {
  return (
    <div className="main">
      <div className="main_section">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Navbar />
          <div className="px-5">
            <Sort />
          </div>
        </div>
      </div>
    </div>
  );
}
