import Head from "next/head";
import Navbar from "../components/Navbar";
import Main from "../components/Main";

export default function Home({ rides, user }) {
  return (
    <div className="main">
      <div className="main_section">
        <Head>
          <title>Edvora</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Navbar user={user} />
          <div className="px-5">
            <Main rides={rides} />
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const rides = await fetch("https://assessment.api.vweb.app/rides").then(
    (response) => response.json()
  );
  const user = await fetch("https://assessment.api.vweb.app/user").then(
    (response) => response.json()
  );
  return {
    props: {
      rides,
      user,
    },
  };
}
